source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!



target 'YNKit' do

pod 'JLRoutes', '~> 2.1'
pod 'YYKit', '1.0.9'
pod 'AFNetworking', '4.0.1'
pod 'Alamofire', '5.8.0'

end
